// Comment out this line when using as DLL
#define amalgamate_conditional_STATIC
#ifndef AMALGAMATE_CONDITIONAL_H
#define AMALGAMATE_CONDITIONAL_H

/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef AMALGAMATE_CONDITIONAL_BAKE_CONFIG_H
#define AMALGAMATE_CONDITIONAL_BAKE_CONFIG_H

/* Headers of public dependencies */

/* Headers of private dependencies */
#ifdef amalgamate_conditional_EXPORTS
// Comment out this line when using as DLL
#define amalgamate_private_STATIC
#ifndef AMALGAMATE_PRIVATE_H
#define AMALGAMATE_PRIVATE_H

/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef AMALGAMATE_PRIVATE_BAKE_CONFIG_H
#define AMALGAMATE_PRIVATE_BAKE_CONFIG_H

/* Headers of public dependencies */
/* No dependencies */

/* Headers of private dependencies */
#ifdef amalgamate_private_EXPORTS
// Comment out this line when using as DLL
#define amalgamate_leaf_STATIC
#ifndef AMALGAMATE_LEAF_H
#define AMALGAMATE_LEAF_H

/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef AMALGAMATE_LEAF_BAKE_CONFIG_H
#define AMALGAMATE_LEAF_BAKE_CONFIG_H

/* Headers of public dependencies */
/* No dependencies */

/* Convenience macro for exporting symbols */
#ifndef amalgamate_leaf_STATIC
#if defined(amalgamate_leaf_EXPORTS) && (defined(_MSC_VER) || defined(__MINGW32__))
  #define AMALGAMATE_LEAF_API __declspec(dllexport)
#elif defined(amalgamate_leaf_EXPORTS)
  #define AMALGAMATE_LEAF_API __attribute__((__visibility__("default")))
#elif defined(_MSC_VER)
  #define AMALGAMATE_LEAF_API __declspec(dllimport)
#else
  #define AMALGAMATE_LEAF_API
#endif
#else
  #define AMALGAMATE_LEAF_API
#endif

#endif

AMALGAMATE_LEAF_API int amalgamate_leaf_value(void);

#endif

#endif

/* Convenience macro for exporting symbols */
#ifndef amalgamate_private_STATIC
#if defined(amalgamate_private_EXPORTS) && (defined(_MSC_VER) || defined(__MINGW32__))
  #define AMALGAMATE_PRIVATE_API __declspec(dllexport)
#elif defined(amalgamate_private_EXPORTS)
  #define AMALGAMATE_PRIVATE_API __attribute__((__visibility__("default")))
#elif defined(_MSC_VER)
  #define AMALGAMATE_PRIVATE_API __declspec(dllimport)
#else
  #define AMALGAMATE_PRIVATE_API
#endif
#else
  #define AMALGAMATE_PRIVATE_API
#endif

#endif

AMALGAMATE_PRIVATE_API int amalgamate_private_value(void);

#endif

#endif

/* Convenience macro for exporting symbols */
#ifndef amalgamate_conditional_STATIC
#if defined(amalgamate_conditional_EXPORTS) && (defined(_MSC_VER) || defined(__MINGW32__))
  #define AMALGAMATE_CONDITIONAL_API __declspec(dllexport)
#elif defined(amalgamate_conditional_EXPORTS)
  #define AMALGAMATE_CONDITIONAL_API __attribute__((__visibility__("default")))
#elif defined(_MSC_VER)
  #define AMALGAMATE_CONDITIONAL_API __declspec(dllimport)
#else
  #define AMALGAMATE_CONDITIONAL_API
#endif
#else
  #define AMALGAMATE_CONDITIONAL_API
#endif

#endif

AMALGAMATE_CONDITIONAL_API int amalgamate_conditional_value(void);

#endif

